// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file v1/auth.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/auth.proto.
 */
export const file_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Cg12MS9hdXRoLnByb3RvIiAKDlVwZGF0ZUp3dFRva2VuEg4KBmFjY2VzcxgBIAEoCWIGcHJvdG8z");

/**
 * @generated from message UpdateJwtToken
 */
export type UpdateJwtToken = Message<"UpdateJwtToken"> & {
  /**
   * @generated from field: string access = 1;
   */
  access: string;
};

/**
 * Describes the message UpdateJwtToken.
 * Use `create(UpdateJwtTokenSchema)` to create a new message.
 */
export const UpdateJwtTokenSchema: GenMessage<UpdateJwtToken> = /*@__PURE__*/
  messageDesc(file_v1_auth, 0);

